// Code generated by Slice Machine. DO NOT EDIT.
import { defineSliceZoneComponents } from "@prismicio/vue";
import { defineAsyncComponent } from "vue";

export const components = defineSliceZoneComponents({
	rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
});
